Vagrant.configure("2") do |config|
    #Nodes 101 102 ...
    (1..3).each do |i|

        config.vm.define "node#{i}" do |node|

        # 设置虚拟机的Box
        node.vm.box = "ubuntu/trusty64"

        # 设置虚拟机的主机名
        node.vm.hostname="node#{i}"

        # 设置虚拟机的IP
        node.vm.network "private_network", ip: "192.168.59.10#{i}"

        # 设置主机与虚拟机的共享目录
        node.vm.synced_folder "..", "/opt/gopath/src/github.com/bocheninc/msg-net"

        # VirtaulBox相关配置
        node.vm.provider "virtualbox" do |v|

            # 设置虚拟机的名称
            v.name = "node#{i}"

            # 设置虚拟机的内存大小  
            #v.memory = 2048

            # 设置虚拟机的CPU个数
            v.cpus = 1
        end
  
        # 使用shell脚本进行软件安装和配置
        node.vm.provision "shell", inline: <<-SHELL
          cd /opt/gopath/src/github.com/bocheninc/msg-net/devenv
          ./setup.sh

          cd /home/vagrant
          cat golang.sh > msg-net.sh
          echo "msg-net router --id=10#{i} --address=192.168.59.10#{i}:10590 --discovery=192.168.59.101:10590 &" >> msg-net.sh
          chmod +x msg-net.sh
          ./msg-net.sh
        SHELL

        end
    end
end